export const CHANGE_EXECUTE = "CHANGE_EXECUTE";
export const TRANSFORMING = "TRANSFORMING";
export const SELECT_SHAPE = "SELECT_SHAPE";
export const SHOW_SHAPE_LABEL = "SHOW_SHAPE_LABEL";
export const HIDE_SHAPE_LABEL = "HIDE_SHAPE_LABEL";